Repository MTES-MCT/apilos, pull requests merged in 2024-11, with the labels that each got.

#1651 Bump precommit hooks versions
  .pre-commit-config.yaml
Labels: dependencies, python

#1662 Fix palulos label
  conventions/migrations/0098_alter_convention_financement.py
  programmes/migrations/0117_alter_lot_financement.py
  programmes/models/choices.py
Labels: bug

#1613 Suppression de la description des avenants
  conventions/models/convention.py
  conventions/tests/models/test_convention.py
  ecoloweb/services/resources/sql/importers/convention.sql
  templates/conventions/avenant_list.html
Labels: enhancement

#1635 Extraire les statistique par mois des livraisons de PR
  DEVELOPPEUR.md
  conventions/management/commands/get_delivery_statistics.py
Labels: technical

#1663 fix: use date range instead of year as script parameter
  upload/management/commands/fix_text_and_files_fields.py
Labels: technical
