Repository MTES-MCT/apilos, pull requests merged in 2025-05, with the labels that each got.

#1851 Simplification et mise à jour des messages d'erreur
  apilos_settings/views.py
  conventions/services/avenants.py
  conventions/services/convention_generator.py
  conventions/tests/services/test_other_services.py
  conventions/views/conventions.py
  core/exceptions/handler.py
  core/services.py
  siap/custom_middleware.py
  siap/exceptions.py
  siap/siap_client/client.py
  siap/siap_client/tests/test_siap_client_utils.py
  siap/siap_client/utils.py
  templates/500.html
  users/tests/test_views.py
Labels: enhancement

#1857 Suppression de la version dans docker-compose (Dépréciation)
  docker-compose.full-application.yml
  docker-compose.yml
Labels: technical

#1858 ✏️ typo conservées -> conserver
  programmes/views.py
Labels: bug

#1859 [fix] Code insee departement pour la corse
  conventions/management/commands/fix_corse_dpt_code.py
  conventions/management/commands/fix_region_code.py
Labels: bug

#1876 Add commentaire on identification bailleur
  comments/models.py
  templates/conventions/_bailleur_signataire.html
  templates/conventions/recapitulatif/bailleur.html
Labels: bug

#1885 Add redirect urls to alerts
  conventions/services/recapitulatif.py
  conventions/tasks.py
  conventions/tests/services/test_recapitulatif_service.py
  siap/siap_client/client.py
Labels: enhancement
