Repository MTES-MCT/apilos, pull requests merged in 2025-04, with the labels that each got.

#1814 Adaptation de l'affichage du résumé de la résiliation de la convention
  templates/common/nav_bar.html
  templates/conventions/denonciation_list.html
  templates/conventions/recapitulatif.html
  templates/conventions/resiliation_list.html
Labels: bug

#1815 Additional emails to ignore for instructors
  conventions/services/recapitulatif.py
  conventions/tests/services/test_recapitulatif_service.py
  users/admin.py
  users/migrations/0026_historicaluser_secondary_email_user_secondary_email.py
  users/models.py
Labels: enhancement

#1805 Permettre à l'utilisateur de visualider toutes les conventions d'une opération
  SIAP-APiLos.md
  comments/models.py
  conventions/admin.py
  conventions/management/commands/export_conventions.py
  conventions/models/convention.py
  conventions/services/search.py
  programmes/services.py
  programmes/tests/test_services.py
  programmes/tests/test_views.py
  programmes/views.py
  siap/siap_client/utils.py
  templates/conventions/convention_list.html
  templates/conventions/from_operation/add_avenants.html
  templates/conventions/from_operation/add_convention.html
  templates/conventions/from_operation/select_operation.html
  templates/conventions/index.html
  templates/layout/base.html
  templates/operations/common/form_header.html
  templates/operations/conventions.html
  templates/settings/users.html
Labels: enhancement

#1823 Ajout d'une mention pour les prêts en cours de signature
  static/files/financement.xlsx
Labels: enhancement

#1834 Exporter une liste de lots pour chaque convention
  programmes/api/operation_serializers.py
  programmes/api/tests/fixtures.py
  programmes/api/tests/test_apis.py
Labels: enhancement

#1826 Suppression de l'envoi de l'email mensuel
  core/worker.py
  users/management/commands/send_monthly_emails.py
  users/tasks.py
  users/tests/test_commands.py
  users/tests/test_tasks.py
Labels: technical

#1827 Installation et déploiement de sphinx pour la documentation
  .github/workflows/publish-docs.yml
  .gitignore
  README.md
  dev-requirements.txt
  doc-requirements.in
  doc-requirements.txt
  docs/API.md
  docs/DEPLOIEMENT.md
  docs/DEVELOPPEUR.md
  docs/ECOLOWEB.md
  docs/PCA_PRA.md
  docs/README.md
  docs/S3_BACKUP.md
  docs/SIAP-APiLos.md
  docs/__init__.py
  docs/_static/configuration_github_pages_apilos.png
  docs/conf.py
  requirements.in
Labels: documentation

#1824 S1092: Avenants : ajouter la page de collationnement
  documents/Avenant-template.docx
  documents/FoyerResidence-Avenant-template.docx
Labels: enhancement

#1837 Mise à jour de la documentation : partie SIAP / API
  api/siap/v0/urls.py
  docs/API.md
  docs/DEPLOIEMENT.md
  docs/DEVELOPPEUR.md
  docs/README.md
  docs/S3_BACKUP.md
  docs/SIAP-APiLos.md
  docs/_static/ArchitectureAPilos.png
  docs/_static/get-token1.png
  docs/_static/get-token2.png
  docs/_static/get-token3.png
  static/img/apilos_db.svg
  static/img/apilos_logo.png
Labels: documentation
