Repository MTES-MCT/apilos, pull requests merged in 2025-07, with the labels that each got.

#1919 New alert on signed
  conventions/services/alertes.py
  conventions/services/recapitulatif.py
  conventions/services/utils.py
  conventions/tasks.py
  conventions/tests/services/test_alertes.py
  conventions/tests/services/test_recapitulatif_service.py
  conventions/tests/services/test_utils.py
  upload/tasks.py
Labels: enhancement

#1926 Upgrade django csp 4.0
  core/settings.py
  requirements.txt
Labels: dependencies

#1933 Doc: docx and pdf generation
  docs/DOC_GENERATION.md
  docs/FEATURE_FLAGS.md
  docs/README.md
Labels: documentation

#1942 prevent IndexError when accessing empty 'loyers' list
  siap/siap_client/utils.py
Labels: bug

#1939 Add date in export file name
  conventions/views/conventions.py
Labels: enhancement

#1943 Fix permission issue on avenant bailleur when bailleur has a parent
  users/models.py
Labels: bug

#1949 Clear le fichier signé au retour à l'instruction
  conventions/services/recapitulatif.py
Labels: bug

#1950 Don't send alertes when admin is DDT
  conventions/services/alertes.py
  conventions/tests/services/test_alertes.py
Labels: bug
