Repository MTES-MCT/apilos, pull requests merged in 2025-02, with the labels that each got.

#1725 revue des styles des xlsx
  static/files/annexes.xlsx
  static/files/cadastre.xlsx
  static/files/communes.xlsx
  static/files/financement.xlsx
  static/files/foyer_residence_logements.xlsx
  static/files/locaux_collectifs.xlsx
  static/files/logements.xlsx
  static/files/logements_edd.xlsx
  static/files/stationnements.xlsx
Labels: bug

#1732 déterminer la natureLogement quand elle est null selon la natureOperation
  conventions/forms/convention_form_financement.py
  conventions/models/convention.py
  conventions/services/convention_generator.py
  conventions/services/financement.py
  conventions/tasks.py
  conventions/templatetags/custom_filters.py
  conventions/tests/views/test_form_steps.py
  conventions/views/avenants.py
  conventions/views/convention_form.py
  documents/FicheCAF-template.docx
  programmes/models/choices.py
  programmes/models/models.py
  programmes/tests/test_models.py
  siap/siap_client/tests/test_siap_client_utils.py
  siap/siap_client/utils.py
Labels: enhancement

#1733 psycopg2 est déprécié, vive psycopg
  requirements.in
  requirements.txt
Labels: dependencies, python

#1713 Ajout de financements manquant
  SIAP-APiLos.md
  conventions/admin.py
  conventions/forms/convention_form_financement.py
  conventions/forms/type1and2.py
  conventions/migrations/0101_alter_convention_financement.py
  conventions/models/convention.py
  conventions/tests/services/test_financement_service.py
  programmes/migrations/0122_alter_lot_financement.py
  programmes/models/choices.py
  siap/siap_client/utils.py
  templates/conventions/financement.html
Labels: enhancement

#1738 Ajout d'information lors du log d'erreur
  DEPLOIEMENT.md
  siap/siap_client/client.py
Labels: technical

#1735 Affichage de l'entête des habilitations quand celle-ci existe
  templates/layout/siap/habilitations.html
Labels: enhancement

#1736 S1177: Amélioration de la partie cadastre
  conventions/forms/convention_form_cadatre.py
  conventions/services/cadastre.py
  conventions/tests/services/test_cadastre_service.py
  documents/Foyer-template.docx
  documents/HLM-template.docx
  documents/Residence-template.docx
  documents/SEM-template.docx
  documents/Type1-template.docx
  documents/Type2-template.docx
  programmes/migrations/0123_referencecadastrale_autre_and_more.py
  programmes/models/models.py
  static/files/cadastre.xlsx
  templates/conventions/cadastre.html
Labels: enhancement

#1734 Fix upload signée preview
  conventions/tests/views/test_preview_view.py
  conventions/urls.py
  conventions/views/conventions.py
  templates/conventions/upload_signed/preview_document.html
  templates/conventions/upload_signed/signature_date.html
Labels: bug, escalation

#1746 Fix creation simplifiee
  conventions/services/from_operation.py
Labels: bug

#1745 [fix] Ajout d'une convention depuis une opération
  conventions/tests/views/test_from_operation_views.py
  conventions/views/convention_form_from_operation.py
  templates/conventions/from_operation/select_operation_list.html
Labels: bug

#1747 Allow to update code_insee_departement in admin
  programmes/admin.py
Labels: technical

#1726 Suppression de la notion de financement sur le modèle convention
  conventions/admin.py
  conventions/fixtures/conventions_for_tests.json
  conventions/management/commands/update_financement.py
  conventions/migrations/0102_remove_convention_financement.py
  conventions/models/convention.py
  conventions/services/search.py
  conventions/services/selection.py
  conventions/tests/factories.py
  conventions/tests/models/test_convention.py
  conventions/tests/services/test_financement_service.py
  conventions/tests/services/test_from_operation.py
  conventions/tests/services/test_search.py
  conventions/tests/services/test_selection_service.py
  conventions/tests/views/test_selection_view.py
  dataset_staging.json
  programmes/api/operation_serializers.py
  programmes/api/tests/fixtures.py
  programmes/api/tests/test_apis.py
  programmes/models/models.py
  programmes/services.py
  siap/siap_client/tests/test_siap_client_utils.py
  siap/siap_client/utils.py
  templates/conventions/financement.html
  templates/settings/delegataires/preview.html
Labels: technical

#1754 Bump certifi from v2023.07.22 to v2024.1.31
  dev-requirements.txt
  requirements.txt
Labels: dependencies, python

#1753 Bump urllib3 from v2.0.7 to v2.3.0
  dev-requirements.txt
  requirements.txt
Labels: dependencies, python

#1751 Ajout de l'envoi d'une erreur Sentry si on tombe dans le edge case RENO_LF
  siap/siap_client/utils.py
Labels: enhancement

#1750 Les financements PSH ne font pas l'objet de conventionnement
  conventions/migrations/0102_alter_convention_financement.py
  programmes/migrations/0124_alter_lot_financement.py
  programmes/models/choices.py
Labels: enhancement

#1752 Use parent bailleur in avenant document
  conventions/models/convention.py
  conventions/services/convention_generator.py
  conventions/signals.py
  documents/Avenant-template.docx
  documents/FoyerResidence-Avenant-template.docx
Labels: bug

#1755 Use SIAP_ASSISTANCE_URL in error messsages
  conventions/views/convention_form_from_operation.py
  conventions/views/conventions.py
  core/context_processor.py
  core/settings.py
  programmes/services.py
  templates/403.html
  templates/404.html
  templates/500.html
  templates/conventions/convention_list.html
  templates/conventions/from_operation/select_operation_list.html
  templates/conventions/home/instructeur_no_convention.html
  templates/conventions/submitted.html
Labels: enhancement

#1756 Fix typo in residence template
  documents/Residence-template.docx
Labels: bug

#1758 Utiliser noreferrer pour tous les liens target blank
  static/img/apilos_db.svg
  templates/403.html
  templates/404.html
  templates/500.html
  templates/common/FAQ_link.html
  templates/conventions/_bailleur_entreprise.html
  templates/conventions/actions/generate_convention.html
  templates/conventions/cadastre.html
  templates/conventions/common/form_logements.html
  templates/conventions/convention_list.html
  templates/conventions/edd.html
  templates/conventions/finalisation/validation.html
  templates/conventions/financement.html
  templates/conventions/from_operation/select_operation_list.html
  templates/conventions/home/bailleur_no_convention.html
  templates/conventions/home/instructeur_no_convention.html
  templates/conventions/submitted.html
  templates/layout/footer.html
  templates/layout/header_cerbere.html
  templates/layout/header_no_cerbere.html
Labels: technical

#1760 Oubli de l'affichage de financement sur les tableaux de conventions
  templates/conventions/convention_list.html
  templates/conventions/financement.html
Labels: bug

#1761 Fix regression after import_mapping became a string
  conventions/services/upload_objects.py
Labels: bug, escalation

#1765 Fix import annexes
  conventions/services/upload_objects.py
Labels: bug
