Repository MTES-MCT/apilos, pull requests merged in 2025-01, with the labels that each got.

#1712 [WIP Tests] Update avenants logements
  apilos_settings/models.py
  conventions/forms/convention_form_logements.py
  conventions/models/pret.py
  conventions/services/convention_generator.py
  conventions/services/conventions.py
  conventions/services/logements.py
  conventions/services/upload_objects.py
  conventions/services/utils.py
  conventions/tests/fixtures.py
  conventions/tests/services/test_convention_generator.py
  conventions/tests/services/test_logements_service.py
  conventions/tests/views/test_logements_view.py
  conventions/views/convention_form.py
  conventions/views/conventions.py
  documents/Avenant-template.docx
  programmes/migrations/0121_logementcorrigee_logementcorrigeesansloyer_and_more.py
  programmes/models/models.py
  static/files/logements_corrigee.xlsx
  static/files/logements_corrigee_sans_loyer.xlsx
  static/files/logements_sans_loyer.xlsx
  static/js/logements-table.js
  templates/common/form/download_upload_form.html
  templates/conventions/common/form_foyer_residence_logements.html
  templates/conventions/common/form_logements.html
  templates/conventions/common/formset_logements.html
  templates/conventions/recapitulatif.html
  templates/conventions/recapitulatif/logements.html
Labels: enhancement

#1714 Suppression du déploiement sur les environnements dépréciés
  .github/workflows/push-branch-main.yml
  .github/workflows/push-version-tag.yml
Labels: technical

#1715 Fix file uploads
  templates/conventions/cadastre.html
  templates/conventions/common/form_annexes.html
  templates/conventions/common/form_collectif.html
  templates/conventions/common/form_stationnements.html
  templates/conventions/edd.html
  templates/conventions/financement.html
  templates/settings/delegataires/form.html
Labels: bug

#1719 Fix fiche caf after schema update
  conventions/views/conventions.py
Labels: bug

#1721 Fix get or create lots from SIAP operation
  siap/siap_client/utils.py
Labels: bug
