Repository MTES-MCT/apilos, pull requests merged in 2025-03, with the labels that each got.

#1772 Avenants recapitulatif
  conventions/forms/avenant.py
  conventions/services/avenants.py
  conventions/services/logements.py
  conventions/services/recapitulatif.py
  conventions/views/avenants.py
  conventions/views/conventions.py
  static/css/main.css
  templates/conventions/avenant/champ_libre_start.html
  templates/conventions/common/avenants_checkboxes.html
  templates/conventions/new_avenant.html
  templates/conventions/post_action.html
  templates/conventions/recapitulatif.html
  templates/conventions/recapitulatif/_card.html
  templates/conventions/recapitulatif/annexes.html
  templates/conventions/recapitulatif/annexes_inner_content.html
  templates/conventions/recapitulatif/bailleur.html
  templates/conventions/recapitulatif/champ_libre.html
  templates/conventions/recapitulatif/collectif.html
  templates/conventions/recapitulatif/collectif_inner_content.html
  templates/conventions/recapitulatif/commentaires.html
  templates/conventions/recapitulatif/financement.html
  templates/conventions/recapitulatif/foyer_residence_logements.html
  templates/conventions/recapitulatif/logements.html
  templates/conventions/recapitulatif/operation.html
  templates/conventions/recapitulatif/uncheck_modal.html
Labels: enhancement

#1787 Bump django from 5.1.6 to 5.1.7
  dev-requirements.txt
  requirements.in
  requirements.txt
Labels: dependencies, python

#1788 Récupération du signataire parent depuis le bailleur quand il n'existe pas sur l'objet convention
  conventions/services/convention_generator.py
  conventions/tests/services/test_convention_generator.py
  documents/Avenant-template.docx
  documents/FoyerResidence-Avenant-template.docx
  documents/HLM-template.docx
  documents/Residence-template.docx
  documents/SEM-template.docx
  documents/Type1-template.docx
  documents/Type2-template.docx
Labels: bug, escalation

#1789 Prise en charge des opérations qui mélangent des aides à conventionner et d'autres sans conventionnement
  siap/siap_client/tests/test_siap_client_utils.py
  siap/siap_client/utils.py
  templates/500.html
Labels: bug

#1790 Ajout de commande dans le Makefile
  Makefile
Labels: technical

#1801 Fix convention from operation bailleur privé
  siap/siap_client/utils.py
Labels: bug

#1803 Avenants edd
  conventions/tests/views/test_form_steps.py
  conventions/urls.py
  conventions/views/avenants.py
  conventions/views/convention_form.py
  conventions/views/convention_form_edd.py
  documents/Avenant-template.docx
  documents/FoyerResidence-Avenant-template.docx
  templates/conventions/recapitulatif.html
  templates/conventions/recapitulatif/edd.html
Labels: enhancement

#1810 Fix tableau annexes hidden on conventions
  templates/conventions/recapitulatif/annexes.html
Labels: bug, escalation

#1811 Add references to some templates
  documents/Foyer-template.docx
  documents/Residence-template.docx
Labels: bug
