Repository MTES-MCT/apilos, pull requests merged in 2025-08, with the labels that each got.

#1952 feat: ajout des dueux statuts "publication" et "publication_en_cours"
  conventions/forms/convention_form_dates.py
  conventions/migrations/0104_convention_nom_fichier_publication_spf_and_more.py
  conventions/models/choices.py
  conventions/models/convention.py
  conventions/services/alertes.py
  conventions/services/conventions.py
  conventions/services/file.py
  conventions/services/recapitulatif.py
  conventions/services/utils.py
  conventions/templatetags/custom_filters.py
  conventions/tests/custom_filters/test_main_custom_filters.py
  conventions/tests/services/test_alertes.py
  conventions/tests/services/test_recapitulatif_service.py
  conventions/urls.py
  conventions/views/conventions.py
  static/css/main.css
  templates/common/form/input_numero_publication.html
  templates/conventions/actions/back_to_en_publication.html
  templates/conventions/actions/back_to_signie.html
  templates/conventions/actions/send_to_post.html
  templates/conventions/actions/update_date_publication.html
  templates/conventions/actions/upload_publication_document.html
  templates/conventions/common/form_upload_publication_document.html
  templates/conventions/convention_list.html
  templates/conventions/post.html
  templates/conventions/post_action.html
  templates/conventions/preview.html
  templates/conventions/publication/preview_document.html
  templates/conventions/publication/publication_date.html
  users/models.py
Labels: enhancement

#1960 Add new statuts in some places
  conventions/models/choices.py
  conventions/templatetags/custom_filters.py
  conventions/views/convention_form_from_operation.py
  users/models.py
Labels: enhancement

#1959 Doc adresse
  docs/ADRESSE.md
Labels: documentation

#1962 fix the preview publication document
  conventions/models/choices.py
  conventions/services/file.py
  conventions/services/utils.py
  conventions/views/conventions.py
  templates/common/nav_bar.html
  templates/conventions/post_action.html
  templates/conventions/publication/preview_document.html
Labels: bug

#1977 Remove workaround to not send alerts to ddt
  conventions/services/alertes.py
  conventions/tests/services/test_alertes.py
Labels: technical

#1978 fix nature logement updating when codeFamilleMO is missing.
  siap/siap_client/utils.py
Labels: bug

#1980 Avenants creation: exclude spf fields
  conventions/models/convention.py
Labels: bug

#1979 fix: remove error logging message from the publication date view
  conventions/views/conventions.py
Labels: bug

#1982 Correction du problème de marge des tableaux sur les templates
  documents/Foyer-template.docx
  documents/HLM-template.docx
  documents/Residence-template.docx
  documents/SEM-template.docx
  documents/Type1-template.docx
  documents/Type2-template.docx
Labels: bug
